{
 "title": "LLMInspect ApiStore",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "username",
    "label": "IP Address",
    "query": {}
   },
   { "name": "DS_GRAPHQL", "label": "datasource", "query": "fifemon-graphql-datasource" },
   { "name": "DS_LOKI", "label": "Logs", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Usage Data",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query Query {\n  data: getUserUsageData(collection: \"apistore\", userName: \"$username\", from: \"${__from:date}\", to: \"${__to:date}\") {\n    totalBytes\n    date\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  { "title": "User-specific Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "User Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query Query {\n  data: userStats(\n    startTime: \"${__from:date}\"\n    endTime: \"${__to:date}\"\n    userName: \"$username\"\n    collection: \"apistore\"\n  ) {\n    userName\n    messageCount\n    negativeSentimentCount\n  }\n}\n"
    }
   ]
  },
  { "title": "All Data Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Negative Sentiments",
   "type": "stat",
   "description": "The total number of messages/prompts that were sent that had negative sentiment. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query Query {\n  data: totalStatsWithinTimeInterval(startTime: \"${__from:date:iso}\", endTime: \"${__to:date}\", collection: \"apistore\") {\n    totalNegativeSentiments\n    totalMessages\n  }\n}\n"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "dataPath": "data",
     "endTimePath": "endTime",
     "queryText": "query Query {\n  data: totalStats(collection: \"apistore\") {\n    totalUsers\n  }\n}\n",
     "timePath": "Time"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "LLM Gateway Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{filename=\"/mnt/logs/LLM.log\"} |= ``"
    }
   ]
  }
 ]
}